#!/bin/bash

config=$(cat $1)
secretName=$(echo "$config" | grep "name:" | awk -F: '{print $2}')
keyName=$(echo "$config" | grep "keyName:" | awk -F: '{print $2}')

password="pa55w0rd!"
base64password=$(echo -n $password | base64)

echo "
kind: Secret
apiVersion: v1
metadata:
  name: $secretName
data:
  $keyName: $base64password
"
