apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: my-password
spec:
  encryptedData:
    password: AgAh1cQXLbE/lRy9EaNjhhzSOMIYqh7m3T3OnjxDggZut6cJs0+J57iokiNbZMu8gDObAa5V88Xt0w5NbhygqGrNBcKthXXrYKoVxJ8jIZEDGiuXW1EvAdyoVoMM5p7MFT5xOjpb5MVriHFJ63o9j//7uKO4HpxrtZlAXDt6hXxgkV4DerZARwKYNpv96brt69Ty7AmBR/98RqqTb9q/1yIBTXRClE+BRXsOKDwkfGULsZyCZyH9/9NinkUTqMSgHbZj3OAYwqKbmTbWmK7taxXyuoIPzvmrYJZOmCWU1xGnBCwNJ4qfXQOd+tJ2FZGMMejJryee9xNOAMIiZcXCPRX0BsTs7K2AFgb142DbhS7heQudpk84qwNfovErW0iXxgvRBTfsr0VO69Lw+EZn7c1v5n/owPT/aSQxyRV4PJxAEosGp6tzm+OBMx8SaNGyYp2rmHoKshfaEz0q8v85QnQQUB95yW35iU8alsGGldmN912vDBPhf4Kjv3YzPvkXq0zMZkI4OYdK/qmG4KVYuY6MH0W6xwz3RT1JDtD9aldJwXFEnf8DRKF7ypWM1tXaTo46UzB32P2Y/Snye/Yv+CEleyYgj9CuaBCGQnacnwEIDJBQPde5WjBaEowyJrEProRndGqCO3Jp4psUTelIvvxm14zdQ5kAbjI2i5eUsMk86FG7GXCOkKdKnjUS5p3ozlMCRuiMgii8yTg=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: my-password

